/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { SDKError } from "./sdkerror.js";

/**
 * The request contained an error
 */
export type AccountCreateErrorData = {
  /**
   * A list of errors that occurred.
   */
  errors: Array<models.ErrorAccountCreateError>;
};

/**
 * The request contained an error
 */
export class AccountCreateError extends SDKError {
  /**
   * A list of errors that occurred.
   */
  errors: Array<models.ErrorAccountCreateError>;

  /** The original data that was passed to this error instance. */
  data$: AccountCreateErrorData;

  constructor(
    err: AccountCreateErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.errors = err.errors;

    this.name = "AccountCreateError";
  }
}

/** @internal */
export const AccountCreateError$inboundSchema: z.ZodType<
  AccountCreateError,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(models.ErrorAccountCreateError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new AccountCreateError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type AccountCreateError$Outbound = {
  errors: Array<models.ErrorAccountCreateError$Outbound>;
};

/** @internal */
export const AccountCreateError$outboundSchema: z.ZodType<
  AccountCreateError$Outbound,
  z.ZodTypeDef,
  AccountCreateError
> = z.instanceof(AccountCreateError)
  .transform(v => v.data$)
  .pipe(z.object({
    errors: z.array(models.ErrorAccountCreateError$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountCreateError$ {
  /** @deprecated use `AccountCreateError$inboundSchema` instead. */
  export const inboundSchema = AccountCreateError$inboundSchema;
  /** @deprecated use `AccountCreateError$outboundSchema` instead. */
  export const outboundSchema = AccountCreateError$outboundSchema;
  /** @deprecated use `AccountCreateError$Outbound` instead. */
  export type Outbound = AccountCreateError$Outbound;
}
