/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { SDKError } from "./sdkerror.js";

/**
 * Not authorized to perform this operation
 */
export type ErrorForbiddenData = {
  /**
   * A list of errors that occurred.
   */
  errors: Array<models.ErrorForbiddenError>;
};

/**
 * Not authorized to perform this operation
 */
export class ErrorForbidden extends SDKError {
  /**
   * A list of errors that occurred.
   */
  errors: Array<models.ErrorForbiddenError>;

  /** The original data that was passed to this error instance. */
  data$: ErrorForbiddenData;

  constructor(
    err: ErrorForbiddenData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.errors = err.errors;

    this.name = "ErrorForbidden";
  }
}

/** @internal */
export const ErrorForbidden$inboundSchema: z.ZodType<
  ErrorForbidden,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(models.ErrorForbiddenError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ErrorForbidden(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ErrorForbidden$Outbound = {
  errors: Array<models.ErrorForbiddenError$Outbound>;
};

/** @internal */
export const ErrorForbidden$outboundSchema: z.ZodType<
  ErrorForbidden$Outbound,
  z.ZodTypeDef,
  ErrorForbidden
> = z.instanceof(ErrorForbidden)
  .transform(v => v.data$)
  .pipe(z.object({
    errors: z.array(models.ErrorForbiddenError$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorForbidden$ {
  /** @deprecated use `ErrorForbidden$inboundSchema` instead. */
  export const inboundSchema = ErrorForbidden$inboundSchema;
  /** @deprecated use `ErrorForbidden$outboundSchema` instead. */
  export const outboundSchema = ErrorForbidden$outboundSchema;
  /** @deprecated use `ErrorForbidden$Outbound` instead. */
  export type Outbound = ErrorForbidden$Outbound;
}
