/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cardsCreate } from "../../funcs/cardsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateGenericCardTokenRequest$inboundSchema,
};

export const tool$cardsCreate: ToolDefinition<typeof args> = {
  name: "cards-create",
  description: `Obtain a card token

Obtain a PCI DSS Compliant card token. This token must be used in order to add a card to a user’s DailyPay account.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await cardsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
