/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paychecksRead } from "../../funcs/paychecksRead.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ReadPaycheckRequest$inboundSchema,
};

export const tool$paychecksRead: ToolDefinition<typeof args> = {
  name: "paychecks-read",
  description: `Get a Paycheck object

Returns details about a paycheck object.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await paychecksRead(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
