/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { accountsCreate } from "../funcs/accountsCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useSDKContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type AccountsCreateMutationVariables = {
  request: models.AccountDataInput;
  options?: RequestOptions;
};

export type AccountsCreateMutationData = operations.CreateAccountResponse;

/**
 * Create an Account object
 *
 * @remarks
 * Create an account object to store a person's bank or card information as a destination for funds.
 */
export function useAccountsCreateMutation(
  options?: MutationHookOptions<
    AccountsCreateMutationData,
    Error,
    AccountsCreateMutationVariables
  >,
): UseMutationResult<
  AccountsCreateMutationData,
  Error,
  AccountsCreateMutationVariables
> {
  const client = useSDKContext();
  return useMutation({
    ...buildAccountsCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyAccountsCreate(): MutationKey {
  return ["@dailypay/dailypay", "Accounts", "create"];
}

export function buildAccountsCreateMutation(
  client$: SDKCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: AccountsCreateMutationVariables,
  ) => Promise<AccountsCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyAccountsCreate(),
    mutationFn: function accountsCreateMutationFn({
      request,
      options,
    }): Promise<AccountsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(accountsCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
