/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import * as operations from "../models/operations/index.js";
import { useSDKContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildOrganizationsListQuery,
  OrganizationsListQueryData,
  prefetchOrganizationsList,
  queryKeyOrganizationsList,
} from "./organizationsList.core.js";
export {
  buildOrganizationsListQuery,
  type OrganizationsListQueryData,
  prefetchOrganizationsList,
  queryKeyOrganizationsList,
};

/**
 * List organizations
 *
 * @remarks
 * Get organizations with an optional filter
 */
export function useOrganizationsList(
  request?: operations.ListOrganizationsRequest | undefined,
  options?: QueryHookOptions<OrganizationsListQueryData>,
): UseQueryResult<OrganizationsListQueryData, Error> {
  const client = useSDKContext();
  return useQuery({
    ...buildOrganizationsListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * List organizations
 *
 * @remarks
 * Get organizations with an optional filter
 */
export function useOrganizationsListSuspense(
  request?: operations.ListOrganizationsRequest | undefined,
  options?: SuspenseQueryHookOptions<OrganizationsListQueryData>,
): UseSuspenseQueryResult<OrganizationsListQueryData, Error> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildOrganizationsListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setOrganizationsListData(
  client: QueryClient,
  queryKeyBase: [parameters: { filterBy?: string | undefined }],
  data: OrganizationsListQueryData,
): OrganizationsListQueryData | undefined {
  const key = queryKeyOrganizationsList(...queryKeyBase);

  return client.setQueryData<OrganizationsListQueryData>(key, data);
}

export function invalidateOrganizationsList(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: { filterBy?: string | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Organizations", "list", ...queryKeyBase],
  });
}

export function invalidateAllOrganizationsList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Organizations", "list"],
  });
}
