/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { paychecksRead } from "../funcs/paychecksRead.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useSDKContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type PaychecksReadQueryData = operations.ReadPaycheckResponse;

/**
 * Get a Paycheck object
 *
 * @remarks
 * Returns details about a paycheck object.
 */
export function usePaychecksRead(
  request: operations.ReadPaycheckRequest,
  options?: QueryHookOptions<PaychecksReadQueryData>,
): UseQueryResult<PaychecksReadQueryData, Error> {
  const client = useSDKContext();
  return useQuery({
    ...buildPaychecksReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a Paycheck object
 *
 * @remarks
 * Returns details about a paycheck object.
 */
export function usePaychecksReadSuspense(
  request: operations.ReadPaycheckRequest,
  options?: SuspenseQueryHookOptions<PaychecksReadQueryData>,
): UseSuspenseQueryResult<PaychecksReadQueryData, Error> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildPaychecksReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchPaychecksRead(
  queryClient: QueryClient,
  client$: SDKCore,
  request: operations.ReadPaycheckRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildPaychecksReadQuery(
      client$,
      request,
    ),
  });
}

export function setPaychecksReadData(
  client: QueryClient,
  queryKeyBase: [paycheckId: string],
  data: PaychecksReadQueryData,
): PaychecksReadQueryData | undefined {
  const key = queryKeyPaychecksRead(...queryKeyBase);

  return client.setQueryData<PaychecksReadQueryData>(key, data);
}

export function invalidatePaychecksRead(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[paycheckId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Paychecks", "read", ...queryKeyBase],
  });
}

export function invalidateAllPaychecksRead(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Paychecks", "read"],
  });
}

export function buildPaychecksReadQuery(
  client$: SDKCore,
  request: operations.ReadPaycheckRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<PaychecksReadQueryData>;
} {
  return {
    queryKey: queryKeyPaychecksRead(request.paycheckId),
    queryFn: async function paychecksReadQueryFn(
      ctx,
    ): Promise<PaychecksReadQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(paychecksRead(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyPaychecksRead(paycheckId: string): QueryKey {
  return ["@dailypay/dailypay", "Paychecks", "read", paycheckId];
}
