/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { useSDKContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildPaychecksListQuery,
  PaychecksListQueryData,
  prefetchPaychecksList,
  queryKeyPaychecksList,
} from "./paychecksList.core.js";
export {
  buildPaychecksListQuery,
  type PaychecksListQueryData,
  prefetchPaychecksList,
  queryKeyPaychecksList,
};

/**
 * Get a list of paycheck objects
 *
 * @remarks
 * Returns a collection of paycheck objects. This object details a person's pay and pay period.
 */
export function usePaychecksList(
  request?: operations.ListPaychecksRequest | undefined,
  options?: QueryHookOptions<PaychecksListQueryData>,
): UseQueryResult<PaychecksListQueryData, Error> {
  const client = useSDKContext();
  return useQuery({
    ...buildPaychecksListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a list of paycheck objects
 *
 * @remarks
 * Returns a collection of paycheck objects. This object details a person's pay and pay period.
 */
export function usePaychecksListSuspense(
  request?: operations.ListPaychecksRequest | undefined,
  options?: SuspenseQueryHookOptions<PaychecksListQueryData>,
): UseSuspenseQueryResult<PaychecksListQueryData, Error> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildPaychecksListQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setPaychecksListData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      filterJobId?: string | undefined;
      filterStatus?: models.FilterPaycheckStatus | undefined;
      filterDepositExpectedAtGte?: Date | undefined;
      filterDepositExpectedAtLt?: Date | undefined;
      filterPayPeriodEndsAtGte?: Date | undefined;
      filterPayPeriodEndsAtLt?: Date | undefined;
      filterPayPeriodStartsAtGte?: Date | undefined;
      filterPayPeriodStartsAtLt?: Date | undefined;
      filterBy?: string | undefined;
    },
  ],
  data: PaychecksListQueryData,
): PaychecksListQueryData | undefined {
  const key = queryKeyPaychecksList(...queryKeyBase);

  return client.setQueryData<PaychecksListQueryData>(key, data);
}

export function invalidatePaychecksList(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      filterJobId?: string | undefined;
      filterStatus?: models.FilterPaycheckStatus | undefined;
      filterDepositExpectedAtGte?: Date | undefined;
      filterDepositExpectedAtLt?: Date | undefined;
      filterPayPeriodEndsAtGte?: Date | undefined;
      filterPayPeriodEndsAtLt?: Date | undefined;
      filterPayPeriodStartsAtGte?: Date | undefined;
      filterPayPeriodStartsAtLt?: Date | undefined;
      filterBy?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Paychecks", "list", ...queryKeyBase],
  });
}

export function invalidateAllPaychecksList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Paychecks", "list"],
  });
}
