/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { peopleRead } from "../funcs/peopleRead.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useSDKContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type PeopleReadQueryData = operations.ReadPersonResponse;

/**
 * Get a person object
 *
 * @remarks
 * Returns details about a person.
 */
export function usePeopleRead(
  request: operations.ReadPersonRequest,
  options?: QueryHookOptions<PeopleReadQueryData>,
): UseQueryResult<PeopleReadQueryData, Error> {
  const client = useSDKContext();
  return useQuery({
    ...buildPeopleReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a person object
 *
 * @remarks
 * Returns details about a person.
 */
export function usePeopleReadSuspense(
  request: operations.ReadPersonRequest,
  options?: SuspenseQueryHookOptions<PeopleReadQueryData>,
): UseSuspenseQueryResult<PeopleReadQueryData, Error> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildPeopleReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchPeopleRead(
  queryClient: QueryClient,
  client$: SDKCore,
  request: operations.ReadPersonRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildPeopleReadQuery(
      client$,
      request,
    ),
  });
}

export function setPeopleReadData(
  client: QueryClient,
  queryKeyBase: [personId: string],
  data: PeopleReadQueryData,
): PeopleReadQueryData | undefined {
  const key = queryKeyPeopleRead(...queryKeyBase);

  return client.setQueryData<PeopleReadQueryData>(key, data);
}

export function invalidatePeopleRead(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[personId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "People", "read", ...queryKeyBase],
  });
}

export function invalidateAllPeopleRead(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "People", "read"],
  });
}

export function buildPeopleReadQuery(
  client$: SDKCore,
  request: operations.ReadPersonRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<PeopleReadQueryData>;
} {
  return {
    queryKey: queryKeyPeopleRead(request.personId),
    queryFn: async function peopleReadQueryFn(
      ctx,
    ): Promise<PeopleReadQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(peopleRead(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyPeopleRead(personId: string): QueryKey {
  return ["@dailypay/dailypay", "People", "read", personId];
}
