/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import * as operations from "../models/operations/index.js";
import { useSDKContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildTransfersReadQuery,
  prefetchTransfersRead,
  queryKeyTransfersRead,
  TransfersReadQueryData,
} from "./transfersRead.core.js";
export {
  buildTransfersReadQuery,
  prefetchTransfersRead,
  queryKeyTransfersRead,
  type TransfersReadQueryData,
};

/**
 * Get a transfer object
 *
 * @remarks
 * Returns details about a transfer of money from one account to another.
 *
 * Created when a person takes an advance against a future paycheck, or on a daily basis when available balance is updated based on current employment.
 */
export function useTransfersRead(
  request: operations.ReadTransferRequest,
  options?: QueryHookOptions<TransfersReadQueryData>,
): UseQueryResult<TransfersReadQueryData, Error> {
  const client = useSDKContext();
  return useQuery({
    ...buildTransfersReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Get a transfer object
 *
 * @remarks
 * Returns details about a transfer of money from one account to another.
 *
 * Created when a person takes an advance against a future paycheck, or on a daily basis when available balance is updated based on current employment.
 */
export function useTransfersReadSuspense(
  request: operations.ReadTransferRequest,
  options?: SuspenseQueryHookOptions<TransfersReadQueryData>,
): UseSuspenseQueryResult<TransfersReadQueryData, Error> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildTransfersReadQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setTransfersReadData(
  client: QueryClient,
  queryKeyBase: [
    transferId: string,
    parameters: { include?: string | undefined },
  ],
  data: TransfersReadQueryData,
): TransfersReadQueryData | undefined {
  const key = queryKeyTransfersRead(...queryKeyBase);

  return client.setQueryData<TransfersReadQueryData>(key, data);
}

export function invalidateTransfersRead(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [transferId: string, parameters: { include?: string | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Transfers", "read", ...queryKeyBase],
  });
}

export function invalidateAllTransfersRead(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@dailypay/dailypay", "Transfers", "read"],
  });
}
