/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { jobsRead } from "../../funcs/jobsRead.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ReadJobRequest$inboundSchema,
};

export const tool$jobsRead: ToolDefinition<typeof args> = {
  name: "jobs-read",
  description: `Get a job object

Returns details about a person's employment.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await jobsRead(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
