/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationsList } from "../../funcs/organizationsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListOrganizationsRequest$inboundSchema.optional(),
};

export const tool$organizationsList: ToolDefinition<typeof args> = {
  name: "organizations-list",
  description: `List organizations

Get organizations with an optional filter`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await organizationsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
