/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transfersCreate } from "../../funcs/transfersCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateTransferRequest$inboundSchema,
};

export const tool$transfersCreate: ToolDefinition<typeof args> = {
  name: "transfers-create",
  description: `Request a transfer

Request transfer of funds from an \`EARNINGS_BALANCE\` account to a
personal \`DEPOSITORY\` or \`CARD\` account.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transfersCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
