/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ReadJobGlobals = {
  /**
   * The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
   *
   * @remarks
   */
  version?: number | undefined;
};

export type ReadJobRequest = {
  /**
   * Unique ID of the job
   */
  jobId: string;
};

/** @internal */
export const ReadJobGlobals$inboundSchema: z.ZodType<
  ReadJobGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  version: z.number().int().default(3),
});

/** @internal */
export type ReadJobGlobals$Outbound = {
  version: number;
};

/** @internal */
export const ReadJobGlobals$outboundSchema: z.ZodType<
  ReadJobGlobals$Outbound,
  z.ZodTypeDef,
  ReadJobGlobals
> = z.object({
  version: z.number().int().default(3),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReadJobGlobals$ {
  /** @deprecated use `ReadJobGlobals$inboundSchema` instead. */
  export const inboundSchema = ReadJobGlobals$inboundSchema;
  /** @deprecated use `ReadJobGlobals$outboundSchema` instead. */
  export const outboundSchema = ReadJobGlobals$outboundSchema;
  /** @deprecated use `ReadJobGlobals$Outbound` instead. */
  export type Outbound = ReadJobGlobals$Outbound;
}

export function readJobGlobalsToJSON(readJobGlobals: ReadJobGlobals): string {
  return JSON.stringify(ReadJobGlobals$outboundSchema.parse(readJobGlobals));
}

export function readJobGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<ReadJobGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReadJobGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReadJobGlobals' from JSON`,
  );
}

/** @internal */
export const ReadJobRequest$inboundSchema: z.ZodType<
  ReadJobRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  job_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "job_id": "jobId",
  });
});

/** @internal */
export type ReadJobRequest$Outbound = {
  job_id: string;
};

/** @internal */
export const ReadJobRequest$outboundSchema: z.ZodType<
  ReadJobRequest$Outbound,
  z.ZodTypeDef,
  ReadJobRequest
> = z.object({
  jobId: z.string(),
}).transform((v) => {
  return remap$(v, {
    jobId: "job_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReadJobRequest$ {
  /** @deprecated use `ReadJobRequest$inboundSchema` instead. */
  export const inboundSchema = ReadJobRequest$inboundSchema;
  /** @deprecated use `ReadJobRequest$outboundSchema` instead. */
  export const outboundSchema = ReadJobRequest$outboundSchema;
  /** @deprecated use `ReadJobRequest$Outbound` instead. */
  export type Outbound = ReadJobRequest$Outbound;
}

export function readJobRequestToJSON(readJobRequest: ReadJobRequest): string {
  return JSON.stringify(ReadJobRequest$outboundSchema.parse(readJobRequest));
}

export function readJobRequestFromJSON(
  jsonString: string,
): SafeParseResult<ReadJobRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReadJobRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReadJobRequest' from JSON`,
  );
}
