/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paychecksList } from "../funcs/paychecksList.js";
import { paychecksRead } from "../funcs/paychecksRead.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Paychecks extends ClientSDK {
  /**
   * Get a Paycheck object
   *
   * @remarks
   * Returns details about a paycheck object.
   */
  async read(
    request: operations.ReadPaycheckRequest,
    options?: RequestOptions,
  ): Promise<models.PaycheckData> {
    return unwrapAsync(paychecksRead(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a list of paycheck objects
   *
   * @remarks
   * Returns a collection of paycheck objects. This object details a person's pay and pay period.
   * See [Filtering Paychecks](https://developer.dailypay.com/tag/Filtering#section/Supported-Endpoint-Filters) for a description of filterable fields.
   */
  async list(
    request?: operations.ListPaychecksRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.PaychecksData> {
    return unwrapAsync(paychecksList(
      this,
      request,
      options,
    ));
  }
}
