/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @dailypay/dailypay SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx accountsList.ts
 */

import { SDK } from "@dailypay/dailypay";

const sdk = new SDK({
  version: 3,
  security: {
    oauthUserToken: "<YOUR_OAUTH_USER_TOKEN_HERE>",
  },
});

async function main() {
  const result = await sdk.list({
    filterAccountType: "EARNINGS_BALANCE",
  });

  console.log(result);
}

main().catch(console.error);
