workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    local:
        inputs:
            - location: source/sdks.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/dailypay/dailypay/xapi
targets:
    typescript:
        target: typescript
        source: local
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/dailypay/dailypay/xapi
