# yaml-language-server: $schema=https://raw.githubusercontent.com/speakeasy-api/sdk-gen-config/refs/heads/main/schemas/workflow.schema.json
# $schema=https://raw.githubusercontent.com/speakeasy-api/sdk-gen-config/refs/heads/main/schemas/workflow.schema.json

workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    cloud:
        inputs:
            - location: https://s3.amazonaws.com/dp-devportal-images/oas/openapi.yml
        registry:
            location: registry.speakeasyapi.dev/dailypay/dailypay/xapi
targets:
    typescript:
        target: typescript
        source: cloud
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/dailypay/dailypay/xapi-typescript-code-samples
        testing:
            enabled: true
