/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationRequestToken } from "../funcs/authenticationRequestToken.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Authentication extends ClientSDK {
  /**
   * Request access token
   *
   * @remarks
   * Request a Dailypay user access token, as described in the <a href='https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3'>OAuth2 spec</a>. When grant_type is authorization_code, the code and redirect_uri parameters are required. When grant_type is refresh_token, the refresh_token parameter is required.
   */
  async requestToken(
    request: operations.RequestTokenRequest,
    options?: RequestOptions,
  ): Promise<models.TokenData> {
    return unwrapAsync(authenticationRequestToken(
      this,
      request,
      options,
    ));
  }
}
