// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountGalileoCardInput - An account of type CARD with subtype GALILEO.
type AccountGalileoCardInput struct {
	// The card ID provided by Galileo.
	GalileoCardID string `json:"galileo_card_id"`
	// The payment reference number provided by Galileo.
	GalileoPmtRefNo string `json:"galileo_pmt_ref_no"`
}

func (o *AccountGalileoCardInput) GetGalileoCardID() string {
	if o == nil {
		return ""
	}
	return o.GalileoCardID
}

func (o *AccountGalileoCardInput) GetGalileoPmtRefNo() string {
	if o == nil {
		return ""
	}
	return o.GalileoPmtRefNo
}
