// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountDebitCardOutput struct {
	// The first name of the account holder.
	FirstName string `json:"first_name"`
	// The last name of the account holder.
	LastName string `json:"last_name"`
	// The month of the expiration date for the card.
	ExpirationMonth string `json:"expiration_month"`
	// The year of the expiration date for the card.
	ExpirationYear string `json:"expiration_year"`
	// Last four digits of the card number.
	LastFour string `json:"last_four"`
	// The issuer of the card.
	Issuer string `json:"issuer"`
}

func (o *AccountDebitCardOutput) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *AccountDebitCardOutput) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *AccountDebitCardOutput) GetExpirationMonth() string {
	if o == nil {
		return ""
	}
	return o.ExpirationMonth
}

func (o *AccountDebitCardOutput) GetExpirationYear() string {
	if o == nil {
		return ""
	}
	return o.ExpirationYear
}

func (o *AccountDebitCardOutput) GetLastFour() string {
	if o == nil {
		return ""
	}
	return o.LastFour
}

func (o *AccountDebitCardOutput) GetIssuer() string {
	if o == nil {
		return ""
	}
	return o.Issuer
}
