// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountDataOutput - Returns the account object.
type AccountDataOutput struct {
	Data AccountResourceOutput `json:"data"`
}

func (o *AccountDataOutput) GetData() AccountResourceOutput {
	if o == nil {
		return AccountResourceOutput{}
	}
	return o.Data
}
