// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountGalileoCardOutput - An account of type CARD with subtype GALILEO.
type AccountGalileoCardOutput struct {
	// The card ID provided by Galileo.
	GalileoCardID string `json:"galileo_card_id"`
	// The first name of the account holder.
	FirstName string `json:"first_name"`
	// The last name of the account holder.
	LastName string `json:"last_name"`
	// Last four digits of the card number.
	LastFour string `json:"last_four"`
	// The issuer of the card.
	Issuer string `json:"issuer"`
	// The month of the expiration date for the card.
	ExpirationMonth string `json:"expiration_month"`
	// The year of the expiration date for the card.
	ExpirationYear string `json:"expiration_year"`
}

func (o *AccountGalileoCardOutput) GetGalileoCardID() string {
	if o == nil {
		return ""
	}
	return o.GalileoCardID
}

func (o *AccountGalileoCardOutput) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *AccountGalileoCardOutput) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *AccountGalileoCardOutput) GetLastFour() string {
	if o == nil {
		return ""
	}
	return o.LastFour
}

func (o *AccountGalileoCardOutput) GetIssuer() string {
	if o == nil {
		return ""
	}
	return o.Issuer
}

func (o *AccountGalileoCardOutput) GetExpirationMonth() string {
	if o == nil {
		return ""
	}
	return o.ExpirationMonth
}

func (o *AccountGalileoCardOutput) GetExpirationYear() string {
	if o == nil {
		return ""
	}
	return o.ExpirationYear
}
