// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountWiselyCardOutput struct {
	// The first name of the account holder.
	FirstName string `json:"first_name"`
	// The last name of the account holder.
	LastName string `json:"last_name"`
	// The month of the expiration date for the card.
	ExpirationMonth string `json:"expiration_month"`
	// The year of the expiration date for the card.
	ExpirationYear string `json:"expiration_year"`
	// Wisely unique identifier associated to card.
	WiselyToken string `json:"wisely_token"`
	// Last four digits of the card number.
	LastFour string `json:"last_four"`
	// The issuer of the card.
	Issuer string `json:"issuer"`
}

func (o *AccountWiselyCardOutput) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *AccountWiselyCardOutput) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *AccountWiselyCardOutput) GetExpirationMonth() string {
	if o == nil {
		return ""
	}
	return o.ExpirationMonth
}

func (o *AccountWiselyCardOutput) GetExpirationYear() string {
	if o == nil {
		return ""
	}
	return o.ExpirationYear
}

func (o *AccountWiselyCardOutput) GetWiselyToken() string {
	if o == nil {
		return ""
	}
	return o.WiselyToken
}

func (o *AccountWiselyCardOutput) GetLastFour() string {
	if o == nil {
		return ""
	}
	return o.LastFour
}

func (o *AccountWiselyCardOutput) GetIssuer() string {
	if o == nil {
		return ""
	}
	return o.Issuer
}
