// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountDebitCardInput struct {
	// The first name of the account holder.
	FirstName string `json:"first_name"`
	// The last name of the account holder.
	LastName string `json:"last_name"`
	// The month of the expiration date for the card.
	ExpirationMonth string `json:"expiration_month"`
	// The year of the expiration date for the card.
	ExpirationYear string `json:"expiration_year"`
	// The first line of the address for the card.
	AddressLineOne string `json:"address_line_one"`
	// The second line of the address for the card.
	AddressLineTwo *string `json:"address_line_two,omitempty"`
	// The city of the address for the card.
	AddressCity string `json:"address_city"`
	// The two-letter abbreviation of the state in the address for the card.
	AddressState string `json:"address_state"`
	// The zip code of the address for the card.
	AddressZipCode string `json:"address_zip_code"`
	// The country code of the address for the card.
	AddressCountry string `json:"address_country"`
	// A tokenized string replacement for the card data.
	Token string `json:"token"`
	// The issuer of the card.
	Issuer string `json:"issuer"`
}

func (o *AccountDebitCardInput) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *AccountDebitCardInput) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *AccountDebitCardInput) GetExpirationMonth() string {
	if o == nil {
		return ""
	}
	return o.ExpirationMonth
}

func (o *AccountDebitCardInput) GetExpirationYear() string {
	if o == nil {
		return ""
	}
	return o.ExpirationYear
}

func (o *AccountDebitCardInput) GetAddressLineOne() string {
	if o == nil {
		return ""
	}
	return o.AddressLineOne
}

func (o *AccountDebitCardInput) GetAddressLineTwo() *string {
	if o == nil {
		return nil
	}
	return o.AddressLineTwo
}

func (o *AccountDebitCardInput) GetAddressCity() string {
	if o == nil {
		return ""
	}
	return o.AddressCity
}

func (o *AccountDebitCardInput) GetAddressState() string {
	if o == nil {
		return ""
	}
	return o.AddressState
}

func (o *AccountDebitCardInput) GetAddressZipCode() string {
	if o == nil {
		return ""
	}
	return o.AddressZipCode
}

func (o *AccountDebitCardInput) GetAddressCountry() string {
	if o == nil {
		return ""
	}
	return o.AddressCountry
}

func (o *AccountDebitCardInput) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *AccountDebitCardInput) GetIssuer() string {
	if o == nil {
		return ""
	}
	return o.Issuer
}
