// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// DisallowReason - The statuses and required actions are:
// - `null` The person has not been disallowed, and is free to use DailyPay.
// - `INACTIVE` The person has not completed registration or account verification.
// - `DELINQUENT` The person has an outstanding, unrecoverable balance with DailyPay, and should contact support.
// - `BANNED` Access has been revoked.
type DisallowReason string

const (
	DisallowReasonInactive   DisallowReason = "INACTIVE"
	DisallowReasonDelinquent DisallowReason = "DELINQUENT"
	DisallowReasonBanned     DisallowReason = "BANNED"
)

func (e DisallowReason) ToPointer() *DisallowReason {
	return &e
}
func (e *DisallowReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INACTIVE":
		fallthrough
	case "DELINQUENT":
		fallthrough
	case "BANNED":
		*e = DisallowReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DisallowReason: %v", v)
	}
}

// PersonAttributes - A person is a record of someone known to DailyPay. There will only ever be one person record per human being.
type PersonAttributes struct {
	// The statuses and required actions are:
	// - `null` The person has not been disallowed, and is free to use DailyPay.
	// - `INACTIVE` The person has not completed registration or account verification.
	// - `DELINQUENT` The person has an outstanding, unrecoverable balance with DailyPay, and should contact support.
	// - `BANNED` Access has been revoked.
	//
	DisallowReason *DisallowReason `json:"disallow_reason"`
	// The two-letter abbreviation for the state in which the person resides, if located in the United States.  This is used for regulatory compliance purposes.
	//
	StateOfResidence *string `json:"state_of_residence,omitempty"`
}

func (o *PersonAttributes) GetDisallowReason() *DisallowReason {
	if o == nil {
		return nil
	}
	return o.DisallowReason
}

func (o *PersonAttributes) GetStateOfResidence() *string {
	if o == nil {
		return nil
	}
	return o.StateOfResidence
}
