// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PersonRelationshipReadOnly struct {
	Data PersonIdentifier `json:"data"`
}

func (o *PersonRelationshipReadOnly) GetData() PersonIdentifier {
	if o == nil {
		return PersonIdentifier{}
	}
	return o.Data
}
