/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AccountDebitCardOutput = {
  /**
   * The first name of the account holder.
   */
  firstName: string;
  /**
   * The last name of the account holder.
   */
  lastName: string;
  /**
   * The month of the expiration date for the card.
   */
  expirationMonth: string;
  /**
   * The year of the expiration date for the card.
   */
  expirationYear: string;
  /**
   * Last four digits of the card number.
   */
  lastFour: string;
  /**
   * The issuer of the card.
   */
  issuer: string;
};

/** @internal */
export const AccountDebitCardOutput$inboundSchema: z.ZodType<
  AccountDebitCardOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  first_name: z.string(),
  last_name: z.string(),
  expiration_month: z.string(),
  expiration_year: z.string(),
  last_four: z.string(),
  issuer: z.string(),
}).transform((v) => {
  return remap$(v, {
    "first_name": "firstName",
    "last_name": "lastName",
    "expiration_month": "expirationMonth",
    "expiration_year": "expirationYear",
    "last_four": "lastFour",
  });
});

/** @internal */
export type AccountDebitCardOutput$Outbound = {
  first_name: string;
  last_name: string;
  expiration_month: string;
  expiration_year: string;
  last_four: string;
  issuer: string;
};

/** @internal */
export const AccountDebitCardOutput$outboundSchema: z.ZodType<
  AccountDebitCardOutput$Outbound,
  z.ZodTypeDef,
  AccountDebitCardOutput
> = z.object({
  firstName: z.string(),
  lastName: z.string(),
  expirationMonth: z.string(),
  expirationYear: z.string(),
  lastFour: z.string(),
  issuer: z.string(),
}).transform((v) => {
  return remap$(v, {
    firstName: "first_name",
    lastName: "last_name",
    expirationMonth: "expiration_month",
    expirationYear: "expiration_year",
    lastFour: "last_four",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountDebitCardOutput$ {
  /** @deprecated use `AccountDebitCardOutput$inboundSchema` instead. */
  export const inboundSchema = AccountDebitCardOutput$inboundSchema;
  /** @deprecated use `AccountDebitCardOutput$outboundSchema` instead. */
  export const outboundSchema = AccountDebitCardOutput$outboundSchema;
  /** @deprecated use `AccountDebitCardOutput$Outbound` instead. */
  export type Outbound = AccountDebitCardOutput$Outbound;
}

export function accountDebitCardOutputToJSON(
  accountDebitCardOutput: AccountDebitCardOutput,
): string {
  return JSON.stringify(
    AccountDebitCardOutput$outboundSchema.parse(accountDebitCardOutput),
  );
}

export function accountDebitCardOutputFromJSON(
  jsonString: string,
): SafeParseResult<AccountDebitCardOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountDebitCardOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountDebitCardOutput' from JSON`,
  );
}
