/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  AccountResourceInput,
  AccountResourceInput$Outbound,
  AccountResourceInput$outboundSchema,
} from "./accountresourceinput.js";

export type AccountDataInput = {
  data: AccountResourceInput;
};

/** @internal */
export type AccountDataInput$Outbound = {
  data: AccountResourceInput$Outbound;
};

/** @internal */
export const AccountDataInput$outboundSchema: z.ZodType<
  AccountDataInput$Outbound,
  z.ZodTypeDef,
  AccountDataInput
> = z.object({
  data: AccountResourceInput$outboundSchema,
});

export function accountDataInputToJSON(
  accountDataInput: AccountDataInput,
): string {
  return JSON.stringify(
    AccountDataInput$outboundSchema.parse(accountDataInput),
  );
}
