/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AccountResourceOutput,
  AccountResourceOutput$inboundSchema,
} from "./accountresourceoutput.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Returns the account object.
 */
export type AccountDataOutput = {
  data: AccountResourceOutput;
};

/** @internal */
export const AccountDataOutput$inboundSchema: z.ZodType<
  AccountDataOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: AccountResourceOutput$inboundSchema,
});

export function accountDataOutputFromJSON(
  jsonString: string,
): SafeParseResult<AccountDataOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountDataOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountDataOutput' from JSON`,
  );
}
