/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const FilterAccountType = {
  EarningsBalance: "EARNINGS_BALANCE",
  Depository: "DEPOSITORY",
  Card: "CARD",
} as const;
export type FilterAccountType = ClosedEnum<typeof FilterAccountType>;

/** @internal */
export const FilterAccountType$inboundSchema: z.ZodNativeEnum<
  typeof FilterAccountType
> = z.nativeEnum(FilterAccountType);

/** @internal */
export const FilterAccountType$outboundSchema: z.ZodNativeEnum<
  typeof FilterAccountType
> = FilterAccountType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FilterAccountType$ {
  /** @deprecated use `FilterAccountType$inboundSchema` instead. */
  export const inboundSchema = FilterAccountType$inboundSchema;
  /** @deprecated use `FilterAccountType$outboundSchema` instead. */
  export const outboundSchema = FilterAccountType$outboundSchema;
}
