/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  JobAttributesInput,
  JobAttributesInput$Outbound,
  JobAttributesInput$outboundSchema,
} from "./jobattributes.js";
import {
  JobRelationshipsInput,
  JobRelationshipsInput$Outbound,
  JobRelationshipsInput$outboundSchema,
} from "./jobrelationshipsinput.js";

/**
 * A job describes the financial relationship between a person and an organization.
 */
export type Data = {
  type: "jobs";
  id: string;
  attributes?: JobAttributesInput | undefined;
  /**
   * The relationships between the job and other resources, including the accounts to which paychecks from this job are deposited.
   */
  relationships?: JobRelationshipsInput | undefined;
};

export type JobUpdateData = {
  /**
   * A job describes the financial relationship between a person and an organization.
   */
  data: Data;
};

/** @internal */
export type Data$Outbound = {
  type: "jobs";
  id: string;
  attributes?: JobAttributesInput$Outbound | undefined;
  relationships?: JobRelationshipsInput$Outbound | undefined;
};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> =
  z.object({
    type: z.literal("jobs"),
    id: z.string(),
    attributes: JobAttributesInput$outboundSchema.optional(),
    relationships: JobRelationshipsInput$outboundSchema.optional(),
  });

export function dataToJSON(data: Data): string {
  return JSON.stringify(Data$outboundSchema.parse(data));
}

/** @internal */
export type JobUpdateData$Outbound = {
  data: Data$Outbound;
};

/** @internal */
export const JobUpdateData$outboundSchema: z.ZodType<
  JobUpdateData$Outbound,
  z.ZodTypeDef,
  JobUpdateData
> = z.object({
  data: z.lazy(() => Data$outboundSchema),
});

export function jobUpdateDataToJSON(jobUpdateData: JobUpdateData): string {
  return JSON.stringify(JobUpdateData$outboundSchema.parse(jobUpdateData));
}
