/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OrganizationResource,
  OrganizationResource$inboundSchema,
  OrganizationResource$Outbound,
  OrganizationResource$outboundSchema,
} from "./organizationresource.js";

/**
 * Returns details about an organization.
 */
export type OrganizationData = {
  data: OrganizationResource;
};

/** @internal */
export const OrganizationData$inboundSchema: z.ZodType<
  OrganizationData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: OrganizationResource$inboundSchema,
});

/** @internal */
export type OrganizationData$Outbound = {
  data: OrganizationResource$Outbound;
};

/** @internal */
export const OrganizationData$outboundSchema: z.ZodType<
  OrganizationData$Outbound,
  z.ZodTypeDef,
  OrganizationData
> = z.object({
  data: OrganizationResource$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OrganizationData$ {
  /** @deprecated use `OrganizationData$inboundSchema` instead. */
  export const inboundSchema = OrganizationData$inboundSchema;
  /** @deprecated use `OrganizationData$outboundSchema` instead. */
  export const outboundSchema = OrganizationData$outboundSchema;
  /** @deprecated use `OrganizationData$Outbound` instead. */
  export type Outbound = OrganizationData$Outbound;
}

export function organizationDataToJSON(
  organizationData: OrganizationData,
): string {
  return JSON.stringify(
    OrganizationData$outboundSchema.parse(organizationData),
  );
}

export function organizationDataFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationData' from JSON`,
  );
}
