/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FundingSourceResource,
  FundingSourceResource$inboundSchema,
  FundingSourceResource$Outbound,
  FundingSourceResource$outboundSchema,
} from "./fundingsourceresource.js";
import {
  TransferResource,
  TransferResource$inboundSchema,
  TransferResource$Outbound,
  TransferResource$outboundSchema,
} from "./transferresource.js";

/**
 * A list of transfer objects.
 */
export type TransfersData = {
  data: Array<TransferResource>;
  included?: Array<FundingSourceResource> | undefined;
};

/** @internal */
export const TransfersData$inboundSchema: z.ZodType<
  TransfersData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(TransferResource$inboundSchema),
  included: z.array(FundingSourceResource$inboundSchema).optional(),
});

/** @internal */
export type TransfersData$Outbound = {
  data: Array<TransferResource$Outbound>;
  included?: Array<FundingSourceResource$Outbound> | undefined;
};

/** @internal */
export const TransfersData$outboundSchema: z.ZodType<
  TransfersData$Outbound,
  z.ZodTypeDef,
  TransfersData
> = z.object({
  data: z.array(TransferResource$outboundSchema),
  included: z.array(FundingSourceResource$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransfersData$ {
  /** @deprecated use `TransfersData$inboundSchema` instead. */
  export const inboundSchema = TransfersData$inboundSchema;
  /** @deprecated use `TransfersData$outboundSchema` instead. */
  export const outboundSchema = TransfersData$outboundSchema;
  /** @deprecated use `TransfersData$Outbound` instead. */
  export type Outbound = TransfersData$Outbound;
}

export function transfersDataToJSON(transfersData: TransfersData): string {
  return JSON.stringify(TransfersData$outboundSchema.parse(transfersData));
}

export function transfersDataFromJSON(
  jsonString: string,
): SafeParseResult<TransfersData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransfersData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransfersData' from JSON`,
  );
}
