/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TransferAttributesInput,
  TransferAttributesInput$inboundSchema,
  TransferAttributesInput$Outbound,
  TransferAttributesInput$outboundSchema,
} from "./transferattributes.js";
import {
  TransferCreateRelationships,
  TransferCreateRelationships$inboundSchema,
  TransferCreateRelationships$Outbound,
  TransferCreateRelationships$outboundSchema,
} from "./transfercreaterelationships.js";

export type TransferCreateResource = {
  type: "transfers";
  /**
   * The unique identifier of the transfer. Any UUID version is valid, lower-cased.
   */
  id?: string | undefined;
  /**
   * An object representing a transfer of money from one account to another.
   *
   * @remarks
   * Created when a person takes an advance against a future paycheck, or on a daily basis
   * when we update estimated earnings based on current employment.
   */
  attributes: TransferAttributesInput;
  relationships: TransferCreateRelationships;
};

/** @internal */
export const TransferCreateResource$inboundSchema: z.ZodType<
  TransferCreateResource,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("transfers"),
  id: z.string().optional(),
  attributes: TransferAttributesInput$inboundSchema,
  relationships: TransferCreateRelationships$inboundSchema,
});

/** @internal */
export type TransferCreateResource$Outbound = {
  type: "transfers";
  id?: string | undefined;
  attributes: TransferAttributesInput$Outbound;
  relationships: TransferCreateRelationships$Outbound;
};

/** @internal */
export const TransferCreateResource$outboundSchema: z.ZodType<
  TransferCreateResource$Outbound,
  z.ZodTypeDef,
  TransferCreateResource
> = z.object({
  type: z.literal("transfers"),
  id: z.string().optional(),
  attributes: TransferAttributesInput$outboundSchema,
  relationships: TransferCreateRelationships$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransferCreateResource$ {
  /** @deprecated use `TransferCreateResource$inboundSchema` instead. */
  export const inboundSchema = TransferCreateResource$inboundSchema;
  /** @deprecated use `TransferCreateResource$outboundSchema` instead. */
  export const outboundSchema = TransferCreateResource$outboundSchema;
  /** @deprecated use `TransferCreateResource$Outbound` instead. */
  export type Outbound = TransferCreateResource$Outbound;
}

export function transferCreateResourceToJSON(
  transferCreateResource: TransferCreateResource,
): string {
  return JSON.stringify(
    TransferCreateResource$outboundSchema.parse(transferCreateResource),
  );
}

export function transferCreateResourceFromJSON(
  jsonString: string,
): SafeParseResult<TransferCreateResource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransferCreateResource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransferCreateResource' from JSON`,
  );
}
