name: Release Please
on:
  push:
    branches:
      - DEVREL-641
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: '@dailypay/dailypay'
          default-branch: DEVREL-641
          token: ${{ secrets.GITHUB_TOKEN }}