name: "Scan"

on:
  schedule:
    - cron: "0 0 * * *"
  pull-requests:
    types: [published]

inputs:
  branch_name:
    description: Branch name to target scan on
    required: true
    default: main


permissions:
  pull-requests: write
  contents: write
  security-events: write
  id-token: write

jobs:
  scan:
    uses: ./.github/workflows/reusable-scan.yaml
    secrets: inherit
    with:
      branch_name: ${{ inputs.branch_name }}
